### ISSUE TITLE
Server actually does not listen

### ISSUE THREAD

**Issue by mahnunchik** [hexojs/hexo-server#1]
Server have en error (or typing mistake) in one of two lines:
* `startServer(http.createServer(app, port, ip))` https://github.com/hexojs/hexo-server/blob/master/lib/server.js#L24
* `server.listen(port, ip, function(){` https://github.com/hexojs/hexo-server/blob/master/lib/server.js#L47

**Comment by tommy351** [comment]
Fixed in commit 90c8b5f00ca892f76fad12dae0398ccbc3ed9ac4
