### ISSUE TITLE
Updating theme throws EISDIR

### ISSUE THREAD

**Issue by kuzzmi** [hexojs/hexo-server#10]
I receive EISDIR error in this scenario:

1. `hexo server`
2. Update a file in `themes` folder.
3. Receive this: 
```
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EISDIR, read
    at Error (native)
```

**Comment by TomDunn** [comment]
I'm also seeing this issue. If I run hexo server it fails to restart when I change a file, same error message as above.

**Comment by hpfast** [comment]
me too. It happens with any file change, also to content (post files)

**Comment by cazgp** [comment]
Pretty sure this is an issue in chokidar, but I haven't been able to track it down yet. Throwing in a `process.on('uncaughtException')` allows you to keep developing. It's a terrible workaround, but tracking the error down is proving to be quite difficult.

**Comment by leesei** [comment]
We updated chokidar version back [in April](https://github.com/hexojs/hexo-fs/commit/ec8b2527ec1f25bc9e41ebff160f550950997753).
Do this problem still exist?

**Comment by NoahDragon** [comment]
As haven't got any feed back for more than half year. I will close this issue.

Feel free to reopen it, if the issue still there.
