### ISSUE TITLE
Gulpfile for Hexo theme development?

### ISSUE THREAD

**Issue by chrisjlee** [hexojs/hexo-server#12]
Trying to do theme development.
How does one trigger gulp to reload hexo-server based on a gulp watch?

**Comment by chronzerg** [comment]
hexo-server automatically rebuilds your site when the theme files change. I too have a gulp file which builds my theme. What I do is have both hexo-server and my gulp watch task running at the same time. When changes to the theme's source file occur, gulp updates the theme output files. When the theme output files change, hexo-server updates the site with the new theme.
