### ISSUE TITLE
hexo 3.1 : How to unwatch file change ?

### ISSUE THREAD

**Issue by morris821028** [hexojs/hexo-server#13]
below this command, show rendered articles in public dictionary.
```
$ hexo server -s
```

I found that if change markdown file, and hexo server show old data in expect. However, why nodejs run in background and spend a lot of CPU and Memory.

monitor `Evented I/O for V8 javascript`, right ?

**Comment by leesei** [comment]
The node instance was still there to serve your files to browser.
With `-s` it is not watching your file and does not consume much resources.
Please provide statistics if it does otherwise.

**Comment by leesei** [comment]
On the other hand `hexo` command would certainly use more resource then pure static HTTP servers like `http-server`, `ecstatic`.
You can use them to server `public/` instead of using `hexo-server`.
