### ISSUE TITLE
hexo-server can not detect my language support correctly

### ISSUE THREAD

**Issue by zekeair** [hexojs/hexo-server#18]
```yaml
language: 
- zh-CN
- en
```

I have `en.yml`and`zh-CN.yml` templates. I change my OS' language and browser's language to English. But the site under hexo-server still convert content of `__()` to simple Chinese. After I arranged `en` to the first, content of `__()` always display English no matter what language setting of OS and browser. 

Does something I misunderstand?

**Comment by NoahDragon** [comment]
This issue shouldn't raise here. 

Please have a look the Hexo plugin i18n, https://github.com/hexojs/hexo-i18n , which is handling the multiple language support.

If the issue still exists, feel free to post there.
