### ISSUE TITLE
--debug flag is not working with node-inspector

### ISSUE THREAD

**Issue by TylerYang** [hexojs/hexo-server#19]
Hi guys, just try to create a new `hexo-server` 3rd party component, when I try to debug the `hexo-server` with `node-inspector`, seems it is not working.  Is there any other way to debug the `hexo-server` ?

**Comment by TylerYang** [comment]
Just found a way to do it,

```shell
node-inspector
cd node_modules/hexo/node_modules/hexo-cli/bin
node --debug hexo serve
```

Hexo => Hexo-Cli(This module then create a Hexo instance and then runHexoCommand) 
So `Hexo-Cli` is the entry point of the whole project.

**Comment by leesei** [comment]
`hexo serve --debug` is a verbose mode to print more log.
It have nothing to do with external module like node-inspector.
Hope you understand.

**Comment by TylerYang** [comment]
I understand the `hexo serve --debug` is a specific mode for the developer to debug. 

Just a small proposal, if we can let the developer to add the breakpoints(with statement `debugger`) to debug their `hexo serve` plugin, then this would help them a lot.
