### ISSUE TITLE
Add support utf8

### ISSUE THREAD

**Issue by hkjorgensen** [hexojs/hexo-server#20]
Hi this is a great part of HEXO, but I wish you would add support for utf8 in the response headers. Having non-english chars like: "æøå" (danish letters) does not work when running `hexo server`. `utf8` needs to be set in the nodejs server :-)

**Comment by gabrfarina** [comment]
Hi, just a quick thought: have you tried adding `<meta charset="UTF-8">` inside your `<head>`?

**Comment by hkjorgensen** [comment]
Thanks! yes, that fixed it :-)

**Comment by gabrfarina** [comment]
Cool, happy to hear that 😄 At this stage, I would also consider closing this issue: I think setting the encoding in the page meta-vars is better than forcing the charset in the server response header.

**Comment by cbas** [comment]
Setting content type per file is a nice workaround. Would still be nice to have a globally configured content type for the server.

1. It would be easier to apply across all files (HTML/SVG/etc) at once.
1. This works with files that do not have meta data, like JSON or plaintext files without BOM.
1. Mimics potential configuration of the production environment (static server or CDN).

**Comment by NoahDragon** [comment]
Glad it has fixed. Close this issue.
