### ISSUE TITLE
Servedsite in language other than what was set when not using -s flag

### ISSUE THREAD

**Issue by FrankV01** [hexojs/hexo-server#28]
I'm doing initial configuration on [my blog (in theory, you could clone and try this yourself)](https://github.com/TheOpenSourceU/TheOpenSourceU.github.io) and after going through steps listed here https://gist.github.com/btfak/18938572f5df000ebe06fbd1872e4e39 I ran the command : `hexo server`

And I noticed the site render in (first) Russian and then when I switched tabs French. Very weird. I eventually tried `hexo server -s` and the pages rendered as expected. 

My conclusion is for whatever reason when it was serving without the `-s` flag it rendered in a (basically) a random language.  I did try to set the `_config.yml` language setting to `en` but that didn't change the result. 

I restarted the server several times.

**Comment by NoahDragon** [comment]
Please run `hexo clean` then `hexo g` to clean up the old info.

**Comment by stevenjoezhang** [comment]
Closing as answered.
