### ISSUE TITLE
Post with a timestamp in the future will not be visible even if defined time had past without restarting server

### ISSUE THREAD

**Issue by Haocen** [hexojs/hexo-server#31]
## Environment Info

Node version(`node -v`):
v6.11.3

Your site `_config.yml` (Optional):
Related config:
```
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
```

Your theme `_config.yml` (Optional): 
N/A

Hexo and Plugin version(`npm ls --depth 0`): 
hexo@3.3.9

## For BUG

 1. BUG description:
If hexo is set not to show future posts, then if the server is started before the post become visible, the post will not be shown even if the timestamp had past.

When doing `hexo g` after the timestamp had past, the post can be generated properly in `public` folder.

 2. The way to reproduce
- Configure hexo not to show post in future.
- Start the hexo server.
- Create a post that will become visible in future.
- Refresh the page without restarting the server after the timestamp goes into past, the post will still not be visible.

 3. Log with hexo <command> --debug
N/A

## Related
https://github.com/hexojs/hexo/issues/188
https://github.com/hexojs/hexo/issues/2776

**Comment by NoahDragon** [comment]
As answered in hexo issues, close this one.
