### ISSUE TITLE
Unix Domain Socked, Named Pipes and HTTPS

### ISSUE THREAD

**Issue by arthurafarias** [hexojs/hexo-server#33]
Hello, I would like to contribute to this project by adding support to unix domain socket, named pipes and https. It is something in the architecture that I would like to suggest. Instead of using ip address and port to listen, I would like to suggest using an url like http://localhost:4000, https://localhost:4000 or file://./path-to-unix-domain-socket-or-windows-named-pipe.

I am currently working on that feature. If you could check and give me some suggestions I would appreciate.

https://github.com/arthurafarias/hexo-server/commit/e903795e9d3516fea5a185ef4e6925de559d8dc1

**Comment by NoahDragon** [comment]
I feel it is good feature, but don't know when it applies?

**Comment by arthurafarias** [comment]
When you need deploy this application behind NGINX. When your server architecture is based in microservices. Take a look at this detailed explanation.

https://www.nginx.com/blog/building-microservices-inter-process-communication/
