### ISSUE TITLE
Serve on both IPv4 and IPv6 interfaces by default

### ISSUE THREAD

**Issue by demurgos** [hexojs/hexo-server#35]
Currently, `hexo serve` only listens to IPv4 intefaces. To get the IPv6 `::1`, you have to pass it explicitly with the `ip` option (but then the server is not bound to the IPv4 interfaces).

Would it be possible to make `hexo serve` listen on all interfaces by default?

**Comment by NoahDragon** [comment]
We recommend using apache or nginx as a server for the static website. The hexo-server is for debugging purpose, we don't plan to expand its functionality to reach a standard server level.

**Comment by demurgos** [comment]
I use nginx on my production server, but wanted to use `hexo serve` for development (as intended). I use IPv6 for my localhost domains by defaults (it helps to spot these kind of errors). This is more a quality of life issue.

It's a pretty easy issue to solve: Node listens on interfaces by default. I'll send a PR later this week when I'll have some time.

**Comment by demurgos** [comment]
Would it be possible to push the updated version to npm?

**Comment by NoahDragon** [comment]
@demurgos will do it shortly.

**Comment by NoahDragon** [comment]
Done. Landed on npm.
