### ISSUE TITLE
A known security vulnerabilities in your dependencies.Please update it.Thx.

### ISSUE THREAD

**Issue by BBBOND** [hexojs/hexo-server#40]
![image](https://user-images.githubusercontent.com/9862759/34093984-33ea9e2e-e406-11e7-98cf-e7087f95ed15.png)

The `send` is dependencied by `connect`.

**Comment by NoahDragon** [comment]
I didn't see connect has the send in its package.json, so not sure it is something can be fixed on Hexo side.

**Comment by BBBOND** [comment]
![image](https://user-images.githubusercontent.com/9862759/34141591-3992f5ee-e4bd-11e7-8be8-6d4b9d2e31a7.png)
![image](https://user-images.githubusercontent.com/9862759/34141604-4e066ea2-e4bd-11e7-9518-e1ee2ac05b17.png)
Here.

**Comment by BBBOND** [comment]
Oh sorry. I find there are different `connect`.
