### ISSUE TITLE
Server should check whether header has already been set to prevent overwriting

### ISSUE THREAD

**Issue by 9662** [hexojs/hexo-server#48]
This line:

https://github.com/hexojs/hexo-server/blob/92338ecfb382434818fec9c653992aaadb8514dc/lib/middlewares/route.js#L33

interferes with my own middleware, which sets `Content-Type` for files that are not recognised by `mime.lookup`, but then the header gets overwritten by the above line.

The router middleware should check if the header has already been set before trying to set its value.

**Comment by tcrowe** [comment]
Hey @9662 :wave: How did you run into that problem? Can you provide a test case?

**Comment by 9662** [comment]
I am afraid I no longer recall the circumstances around this issue, but looking at my activity around the reporting date, I think a realistic test case could be as follows:

Have a generator middleware that extracts event-related custom metadata from the front matter and uses it to produce `.ics` files. Because the generated ICS files would normally be served by `hexo serve` with an inadequate `Content-Type` (possibly `application/octet-stream` or `text/plain`) they would not trigger the desired browser behaviour while testing locally, therefore you will also be needing a filter middleware to add the correct `Content-Type: text/calendar` header. This filter middleware would cause the reported error.

In the end I must have implemented this differently so I never followed up.

**Comment by tcrowe** [comment]
@9662 Oh if there was a solution maybe you can post it. How do you want to proceed? Should we still look for a solution or close it?

**Comment by 9662** [comment]
@tcrowe  Seems like a had an old pull request dealing with this. Let me check if it's salvageable.

**Comment by tcrowe** [comment]
https://github.com/hexojs/hexo-server/pull/49

**Comment by 9662** [comment]
Yup, that's the one. I just rebased and updated.
