### ISSUE TITLE
NPM not updated

### ISSUE THREAD

**Issue by celsomiranda** [hexojs/hexo-server#5]
NPM version 0.0.4 doesn't have the `open` functionality added by @KenPowers . Please consider publishing the updated version.

**Comment by tommy351** [comment]
As you wish. 4112d308538275648f739880c773ca75c9166535

**Comment by celsomiranda** [comment]
Thank you.
Em 27/01/2015 03:55, "Tommy Chen" <notifications@github.com> escreveu:
